site_name: Numerical Linear Algebra
theme:
  name: material
  features:
    - header.autohide
    - navigation.tabs
    - navigation.path
    - navigation.indexes
  font:
    text: Libre Baskerville
  palette:
    # Palette toggle for light mode
    - scheme: default
      primary: deep purple
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      primary: deep purple
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

markdown_extensions:
  - pymdownx.arithmatex:
      generic: true

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

repo_url: https://github.com/LiuShuoJiang/Numerical-Linear-Algebra
repo_name: ShuoJiang Liu

nav:
  - Home: index.md
  - Foundations:
    - Basics/README.md
    - Introduction: Basics/Introduction.md
    - Linear Algebra Review: Basics/Linear_Algebra.md
  - Condition and Stability:
    - Condition and Stability/README.md
    - Conditioning: Condition and Stability/Conditioning.md
    - Stability: Condition and Stability/Stability.md
  - Eigenvalue Problem:
    - Eigenvalue/README.md
    - Introduction: Eigenvalue/Introduction.md
    - QR Factorization: Eigenvalue/QR_Factorization.md
    - Classical Eigenvalue Algorithms: Eigenvalue/Classical_Eigenvalue_Algorithms.md
    - QR Algorithm: Eigenvalue/QR_Algorithm.md
    - Divide and Conquer: Eigenvalue/Divide_and_Conquer.md
    - SVD: Eigenvalue/SVD.md

