site_name: Numerical Linear Algebra
theme:
  name: material
  features:
    - header.autohide
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - navigation.path
    - navigation.indexes
    - navigation.top
    - navigation.footer
    - toc.follow
  font:
    text: Libre Baskerville
  icon:
    logo: material/library-outline
  favicon: assets/favicon.png
  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: deep purple
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: deep purple
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.arithmatex:
      generic: true
  - toc:
      permalink: ⚓︎

extra:
  social:
    - icon: fontawesome/brands/github 
      link: https://liushuojiang.github.io/
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/shuojiang-liu-09a749260/

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

repo_url: https://github.com/LiuShuoJiang/Numerical-Linear-Algebra
repo_name: ShuoJiang Liu

copyright: Copyright &copy; 2023 Shuojiang Liu

nav:
  - Home: index.md
  - Foundations:
    - Basics/README.md
    - Introduction: Basics/Introduction.md
    - Linear Algebra Review: Basics/Linear_Algebra.md
  - Condition and Stability:
    - Condition and Stability/README.md
    - Conditioning: Condition and Stability/Conditioning.md
    - Stability: Condition and Stability/Stability.md
  - Eigenvalue Problem:
    - Eigenvalue/README.md
    - Introduction: Eigenvalue/Introduction.md
    - QR Factorization: Eigenvalue/QR_Factorization.md
    - Classical Eigenvalue Algorithms: Eigenvalue/Classical_Eigenvalue_Algorithms.md
    - QR Algorithm: Eigenvalue/QR_Algorithm.md
    - Divide and Conquer: Eigenvalue/Divide_and_Conquer.md
    - SVD: Eigenvalue/SVD.md
  - Iterative Methods:
    - Iterative Methods/README.md
    - Classical Iteration Methods: Iterative Methods/Classical_Iteration.md
    - General Strategy of Iteration Methods: Iterative Methods/Introduction_to_Iteration.md
    - Projection Methods: Iterative Methods/Projection_Method.md
    - Krylov Subspace: Iterative Methods/Projection_Method_2.md
  - Miscellaneous Topics:
    - Miscellaneous/README.md
    - Least Square Problems: Miscellaneous/Least_Square.md

